### ISSUE TITLE
Fix KS5 demos

### ISSUE THREAD

**Issue by vsnever** [cherab/jet#16]
Running one of the KS5 demonstrations (spectra_76666.py or camera_76666.py) throws the following error:
```
Traceback (most recent call last):
  File "cherab-jet/demos/diagnostic/ks5/spectra_76666.py", line 74, in <module>
    flow_velocity_tor_psi = Interpolate1DCubic(psi_coord, flow_velocity_tor_data)
  File "cherab/core/math/interpolators/interpolators1d.pyx", line 426, in cherab.core.math.interpolators.interpolators1d.Interpolate1DCubic.__init__
  File "cherab/core/math/interpolators/interpolators1d.pyx", line 82, in cherab.core.math.interpolators.interpolators1d._Interpolate1DBase.__init__
ValueError: The f array must be 1D.
```
Probably, this happens because the data arrays returned by the version of SAL currently installed on JET cluster have different indexing order compared to the SAL version that was used when these demos were created.

After making the appropriate changes, I have successfully run these demos, so I'll make a PR shortly.

**Comment by vsnever** [comment]
Fixed in #17.
